# Generated by Django 4.2 on 2023-04-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstore',
            name='attrs',
            field=models.JSONField(default=dict),
        ),
    ]
