# Generated by Django 4.2 on 2023-04-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
