# Generated by Django 4.2 on 2023-04-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.TextField(choices=[('STAFF', 'Staff'), ('SUBSCRIBER', 'Subscriber'), ('OTHER', 'Other')]),
        ),
        migrations.AlterField(
            model_name='userstore',
            name='type',
            field=models.TextField(choices=[('SYSTEM', 'System'), ('APP', 'App')]),
        ),
    ]
