# Generated by Django 4.2 on 2023-05-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_type_alter_userstore_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('مرد', 'Male'), ('زن', 'Female')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('SUBSCRIBER', 'Subscriber'), ('OTHER', 'Other')]),
        ),
        migrations.AlterField(
            model_name='userstore',
            name='type',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('APP', 'App')]),
        ),
    ]
